# Generated by Django 5.1.3 on 2024-12-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='restaurant_location',
            field=models.CharField(default='unknown location', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='restaurant_name',
            field=models.CharField(default='unknown location', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='restaurant_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
