# Generated by Django 5.1.3 on 2024-12-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('res_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=500)),
                ('overall_rating', models.FloatField()),
                ('total_ratings', models.IntegerField()),
                ('price_range', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('max_delivery', models.IntegerField()),
                ('min_delivery', models.IntegerField()),
                ('delivery_time', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('main_location', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
