# Generated by Django 5.1.3 on 2024-12-07 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_restaurant_remove_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='res_id',
            new_name='Res_id',
        ),
    ]
