# Generated by Django 5.1.3 on 2024-12-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_menu_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item',
            field=models.CharField(max_length=255),
        ),
    ]
