# Generated by Django 5.1.3 on 2024-12-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_menu_item'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('Res_id', 'Item_id')},
        ),
    ]
